- La'Tonia/README.md
Hello @Tyler-Toro I did it! But check me.
> added hello msg to readme file

- Anthony/README.md
@Tyler-Toro 
Hi Tyler, please review my updates to the branch and readme file for our class challenge. Thanks!
> Creating Anthony's Branch

- Brandon/README.md
Are these changes to your standard?
> Brandon dev branch

- Jessy/README.md
> Thinking out loud

- James/README.md
> added hola to resolve

- La'Tonia/README.md
- La'Tonia/conversions_practice.py
- La'Tonia/print_hello_python_code_world.py
Hello @Tyler-Toro, I am still getting confused about the main versus branch. Specifically, for this I remembered to change the base, which populated to "main" and then I was confused about whether I need to change "main" to my specific branch before making the pull request.
Please revisit to clarify this and I promise to take better notes for future reference.
> added print hello file and added confession to readme

- Brandon/small_bio.txt
> looking forward to adding to this in the coming mnths

- Anthony/first_python_challenge.py
@Tyler-Toro 
Please review my merge for our first python challenge. Thank you.
> adding first python challenge to pod folder

- Brandon/first_python_challenge.py
let me know if this is clean enough
> first python script

- La'Tonia/first_python_challenge.py
Completed each step of the first python challenge assigned in technical class, and tried to add in a little extra practice.
> 1st python challenge

- Jessy/Temperature_Challenge.py
> Group adding Temp CHallange

- La'Tonia/README.md
- La'Tonia/nba_challenge.py
- La'Tonia/temperature_challenge.py
Hello @Tyler-Toro,
I worked on this before class - glad I did, because it allowed me to double check my work in class. And be intentional about fleshing out my comments/notes. Thank you for making python fun, friendly, and part of my code/web dev future.
Also, thanks so much for the great feedback you always give in the pull request responses.
> adding temperature challenge to pod #1 repo

- Brandon/nba_challenge.py
- Brandon/temperature.py
- challenges/04_bootcamp_primitive_data_types/nba_challenge_instructions.md
Temp and Nba challenges complete.  Hope its to your liking, I know not if I took the long route on some of the answers.  Please let me know if there are things I can do to make it better.  I was up late getting things done.  Football is important to me.
> Wk 2 challenges (primitive data types)

- Anthony/temperature_challenge.py
@Tyler-Toro 
Hi Tyler. Please review my temperature challenge. I tried adding more notes than my last challenge. Thanks.
> Addining the temperate challenge

- Jason/Temperature_Challenge.py
@Jason-Doze , triple check all pull requests are being submitted to the Tyler-toro/pod_number_one/main.
> Fixing pull request for Jason

- La'Tonia/README.md
Hello @Tyler-Toro,
Still working on my README file to get it how I'd like it while learning markdown. Please be patient with me regarding the additional pull requests. Talk soon, stay safe.
> centered main header and added credit to gif

- Jessy/box_office_challenge.py
- Jessy/snippets_challenge.py
- Jessy/stocks_challenge.py
> Here are the two latest challenges

- La'Tonia/box_office_challenge.py
Hello @Tyler-Toro,
Other than going blank on how to implement .join method this challenge felt mostly straightforward. Hopefully, my notes are up to par. Talk soon.
> completed box office challenge and added comments

- challenges/06_bootcamp_logic/snippets_challenge.py
- challenges/06_bootcamp_logic/stocks_challenge.py
- challenges/07_bootcamp_lists/box_office_challenge.py
Hope this is to your liking.  I know you would've wanted it more detailed. Kind of rushed through.
> Snippets, box office and stocks challenges

- James/first_python_challenge.py
- James/snippets_challenge.py
- James/stocks_challenge.py
> first_python_challenge.py

- Jason/box_office_challenge.py
- Jason/nba_challenge.py
- Jason/restaurants_challenge.py
- Jason/snippets_challenge.py
- Jason/stocks_challenge.py
Pushing the challenge for review
> adding stocks challenge to repo

- Anthony/nba_challenge.py
- Anthony/restaurants_challenge.py
- Anthony/snippets_challenge.py
@Tyler-Toro 
Hi Tyler, I added the NBA challenge which is due today. I am not sure if I added others with this.
> Adding NBA Challenge due 9/23

- James/nba_challenge.py
I finished the nba challenge but had trouble with the float conversion
I added the temperature challenge but didn't finish it yet
> nba challenge finished and temperature file add

- Jessy/restaurants_challenge.py
accidentally sent it to the JTC account
> Here is my restaurant challenge. Go Rams!

- La'Tonia/README.md
- La'Tonia/dict_in_dict.py
- La'Tonia/dict_in_list.py
- La'Tonia/functions_practice_oh_my.py
- La'Tonia/list_in_dict.py
- La'Tonia/list_in_list.py
- La'Tonia/loops.py
Hello @Tyler-Toro,
Got some practice in. Not everything happened as expected. Still, I was more successful than not and know we will get more practice. That said, I feel satisfied for the day. Hoping you are well. Stay safe.
> practice per recent modules - dict, list, fn, loops, etc.

- James/box_office
>  box office challenge

- Anthony/box_office_challenge.py
- Anthony/buy_me_a_laptop_challenge.py
- Anthony/restaurants_challenge.py
- Anthony/snippets_challenge.py
- Anthony/stocks_challenge.py
@Tyler-Toro 
I added the snippets challenge and stocks challenge to this commit. Both are due today (Monday), 9/27
> Adding Stocks Challenge and Snippets Challenge, due 9/27

- Jessy/buy_me_a_laptop_challenge.py
I'll keep the laptop I have now, thank you!
> This is lots of fun, looking forward to more

- Jessy/email_ids_challenge.py
> Hard Challenge

- La'Tonia/README.md
- La'Tonia/anagram_practice.py
- La'Tonia/buy_me_a_laptop_challenge.py
- La'Tonia/dice_roll_practice.py
- La'Tonia/email_ids_challenge.py
- La'Tonia/guess_game_practice.py
- La'Tonia/hangman_practice.py
- La'Tonia/interactive_dictionary_practice.py
- La'Tonia/library_challenge.py
- La'Tonia/rock_paper_scissors.py
- La'Tonia/tic_tac_toe.py
Good Day @Tyler-Toro,
Three separate pushes from command line. One pull request:
- email id challenge complete w/comments;
- revisited buy laptop challenge for unanswered questions in comments ... all answered, still - would like walk through of example you posted in Slack if we have an opportunity;
- and used align tag instead of style tag to center JTC header in readme ... also did minor overall edits.
Thanks for your time and energy. Talk soon.
> La tonia branch

- Jason/library_challenge.py
This one was pretty tricky, we were kinda there but not quite.  Interesting to have to add print to calling the function.
> adding library challenge to pod 1 repo

- Jason/exceptions_challenge.py
- Jason/playlist_challenge.py
- Jason/playlist_functions.py
Not sure if I got the bonus feature working completely, but it does seem to work in play count.
> adding playlist functions to pod repo

- Jason/book_challenge.py
- Jason/book_class.py
- Jason/station_planning.py
- Jason/stations_challenge.py
Adding both station files to pod 1 repo.
> Stations Challenge
